spring.datasource.url=jdbc:postgresql://localhost:5432/passwordmanager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.config.import=optional:classpath:application-secrets.properties